import { mkdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { CONTRACT_VERSION } from "../src/version";

const moduleDir = join(__dirname, "..", "generated", "go");
const outDir = join(moduleDir, "config");
mkdirSync(outDir, { recursive: true });

const goModPath = join(moduleDir, "go.mod");
const goMod = `module github.com/demo/config-contracts-go

go 1.24.5
`;
writeFileSync(goModPath, goMod);
console.log(`wrote ${goModPath}`);

const file = join(outDir, "types.go");

const content = `// Code generated by generate-go.ts. DO NOT EDIT.
// Contract version: ${CONTRACT_VERSION}
package config

import (
\t"encoding/json"
\t"fmt"
)

const ContractVersion = "${CONTRACT_VERSION}"

type AssetNetworkDetails struct {
\tChain           string \`json:"chain"\`
\tContractAddress string \`json:"contractAddress,omitempty"\`
\tDecimals        int    \`json:"decimals"\`
}

type Asset struct {
\tDepositSuspended     bool                           \`json:"depositSuspended"\`
\tWithdrawSuspended    bool                           \`json:"withdrawSuspended"\`
\tSymbol               string                         \`json:"symbol"\`
\tName                 string                         \`json:"name"\`
\tIcon                 string                         \`json:"icon"\`
\tCoinGeckoId          string                         \`json:"coinGeckoId"\`
\tMinimumAmountToSweep string                         \`json:"minimumAmountToSweep"\`
\tGasLimit             string                         \`json:"gasLimit"\`
\tNetworks             map[string]AssetNetworkDetails \`json:"networks"\`
\tIsNative             bool                           \`json:"isNative"\`
\tAssetAddress         string                         \`json:"assetAddress"\`
\tAssetType            string                         \`json:"assetType"\`
\tDecimals             int                            \`json:"decimals"\`
\tDisplayDecimals      int                            \`json:"displayDecimals"\`
\tIsHidden             bool                           \`json:"isHidden"\`
}

type Assets []Asset

type WorkspaceSettings struct {
\tEnableExternalValidators *bool \`json:"enableExternalValidators,omitempty"\`
}

type WorkspaceSettingsConfig struct {
\tWorkspaceSettings map[string]WorkspaceSettings \`json:"workspaceSettings"\`
}

type ConfigBundle struct {
\tAssets            Assets                  \`json:"assets"\`
\tWorkspaceSettings WorkspaceSettingsConfig \`json:"workspaceSettings"\`
}

type Manifest struct {
\tContractVersion string   \`json:"contractVersion"\`
\tPublishedAt     string   \`json:"publishedAt"\`
\tGitCommit       string   \`json:"gitCommit"\`
\tKeys            []string \`json:"keys"\`
}

func validateAssetNetworkDetails(key string, n AssetNetworkDetails) error {
\tif n.Chain == "" {
\t\treturn fmt.Errorf("network %q: chain must be non-empty", key)
\t}
\tif n.Decimals < 0 {
\t\treturn fmt.Errorf("network %q: decimals must be >= 0", key)
\t}
\treturn nil
}

func validateAsset(idx int, a Asset) error {
\tif a.Symbol == "" {
\t\treturn fmt.Errorf("asset[%d]: symbol must be non-empty", idx)
\t}
\tif a.Name == "" {
\t\treturn fmt.Errorf("asset[%d]: name must be non-empty", idx)
\t}
\tif a.Icon == "" {
\t\treturn fmt.Errorf("asset[%d] %q: icon must be non-empty", idx, a.Symbol)
\t}
\tif a.CoinGeckoId == "" {
\t\treturn fmt.Errorf("asset[%d] %q: coinGeckoId must be non-empty", idx, a.Symbol)
\t}
\tif a.MinimumAmountToSweep == "" {
\t\treturn fmt.Errorf("asset[%d] %q: minimumAmountToSweep must be non-empty", idx, a.Symbol)
\t}
\tif a.GasLimit == "" {
\t\treturn fmt.Errorf("asset[%d] %q: gasLimit must be non-empty", idx, a.Symbol)
\t}
\tif a.AssetType == "" {
\t\treturn fmt.Errorf("asset[%d] %q: assetType must be non-empty", idx, a.Symbol)
\t}
\tif a.Decimals < 0 {
\t\treturn fmt.Errorf("asset[%d] %q: decimals must be >= 0", idx, a.Symbol)
\t}
\tif a.DisplayDecimals < 0 {
\t\treturn fmt.Errorf("asset[%d] %q: displayDecimals must be >= 0", idx, a.Symbol)
\t}
\tfor nk, n := range a.Networks {
\t\tif err := validateAssetNetworkDetails(nk, n); err != nil {
\t\t\treturn fmt.Errorf("asset[%d] %q: %w", idx, a.Symbol, err)
\t\t}
\t}
\treturn nil
}

func validateAssets(a Assets) error {
\tfor i, v := range a {
\t\tif err := validateAsset(i, v); err != nil {
\t\t\treturn err
\t\t}
\t}
\treturn nil
}

func validateWorkspaceSettingsConfig(c WorkspaceSettingsConfig) error {
\tfor k := range c.WorkspaceSettings {
\t\tif k == "" {
\t\t\treturn fmt.Errorf("workspaceSettings: key must be non-empty")
\t\t}
\t}
\treturn nil
}

func ParseAssets(raw []byte) (Assets, error) {
\tvar a Assets
\tif err := json.Unmarshal(raw, &a); err != nil {
\t\treturn nil, err
\t}
\tif err := validateAssets(a); err != nil {
\t\treturn nil, err
\t}
\treturn a, nil
}

func ParseWorkspaceSettings(raw []byte) (WorkspaceSettingsConfig, error) {
\tvar c WorkspaceSettingsConfig
\tif err := json.Unmarshal(raw, &c); err != nil {
\t\treturn WorkspaceSettingsConfig{}, err
\t}
\tif err := validateWorkspaceSettingsConfig(c); err != nil {
\t\treturn WorkspaceSettingsConfig{}, err
\t}
\treturn c, nil
}

func ParseConfigBundle(raw []byte) (ConfigBundle, error) {
\tvar b ConfigBundle
\tif err := json.Unmarshal(raw, &b); err != nil {
\t\treturn ConfigBundle{}, err
\t}
\tif err := validateAssets(b.Assets); err != nil {
\t\treturn ConfigBundle{}, err
\t}
\tif err := validateWorkspaceSettingsConfig(b.WorkspaceSettings); err != nil {
\t\treturn ConfigBundle{}, err
\t}
\treturn b, nil
}
`;

writeFileSync(file, content);
console.log(`wrote ${file}`);
